# Generated by Django 5.1.4 on 2025-01-19 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_fotografia_catedoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotografia',
            old_name='catedoria',
            new_name='categoria',
        ),
    ]
